# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.ssh.insert_key = false

  config.vm.define "vagrant1" do |vagrant1|
      vagrant1.vm.network "private_network", ip: "192.168.34.11"
      vagrant1.vm.hostname = "vagrant1"
      vagrant1.vm.provider "virtualbox" do |v|
          v.memory = 1024
      end
  end

  config.vm.define "vagrant2" do |vagrant2|
      vagrant2.vm.network "private_network", ip: "192.168.34.12"
      vagrant2.vm.hostname = "vagrant2"
      vagrant2.vm.provider "virtualbox" do |v|
          v.memory = 1024
      end
  end

  config.vm.define "vagrant3" do |vagrant3|
      vagrant3.vm.network "private_network", ip: "192.168.34.13"
      vagrant3.vm.hostname = "vagrant3"
      vagrant3.vm.provider "virtualbox" do |v|
          v.memory = 1024
      end
  end

  config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "playbook.yml"
  end

end
