---
- name: Copy image to nodes storage
  copy:
    src: "{{ contrass_push_image }}.{{ commit_id }}"
    dest: /tmp/{{ image_name }}.{{ commit_id }}.tar
    mode: 0644

- name: Check if image exists
  command: docker images
  register: contrass_push_docker_images
  changed_when: False

- name: Load the image on all slaves
  action: shell docker load -i /tmp/{{ image_name }}.{{ commit_id }}.tar
  when: not image_name in contrass_push_docker_images.stdout or not commit_id in contrass_push_docker_images.stdout
