---
# image
- name: Copy image to nodes storage
  copy:
    src: "{{ ganomede_challenges_image }}.{{ ganomede_challenges_git_version }}"
    dest: /tmp/{{ ganomede_challenges_image_name }}.{{ ganomede_challenges_git_version }}.tar
    mode: 0644

- name: Check if image exists on slaves
  command: docker images {{ ganomede_challenges_image_name }}
  register: ganomede_challenges_docker_images
  changed_when: False

- name: Load the image on all slaves
  action: shell docker load -i /tmp/{{ ganomede_challenges_image_name }}.{{ ganomede_challenges_git_version }}.tar
  when: not ganomede_challenges_git_version in ganomede_challenges_docker_images.stdout
