---
- name: Retrieve the git
  git:
    repo: git@github.com:j3k0/ganomede-challenges.git
    version: "{{ ganomede_challenges_git_version }}"
    dest: "{{ ganomede_challenges_git_dest }}"

- name: Create image storage
  file:
    path: "{{ ganomede_challenges_git_dest }}/docker-images"
    state: directory
    mode: 0755

# Prepare image

- name: Check or build image
  docker_image:
    path: "{{ ganomede_challenges_git_dest }}"
    name: "{{ ganomede_challenges_image_name }}"
    tag: "{{ ganomede_challenges_git_version }}"
    state: present

- name: Save the image
  command: docker save -o {{ ganomede_challenges_image }}.{{ ganomede_challenges_git_version }} {{ ganomede_challenges_image_name }}:{{ ganomede_challenges_git_version }}
  args:
    creates: "{{ ganomede_challenges_image }}.{{ ganomede_challenges_git_version }}"

