---
- hosts: all
  become: true

  pre_tasks:
    # Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
    # Will include all hosts the playbook is run on.
    # Inspired from http://xmeblog.blogspot.com/2013/06/ansible-dynamicaly-update-etchosts.html
    - name: "Build hosts file "
      lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].tun0 }} {{item}}" state=present
      when: hostvars[item].tun0 is defined
      with_items: "{{ groups['all'] }}"

    - name: "Build hosts file "
      lineinfile: dest=/etc/hosts regexp='.*tun0$' line="{{ tun0 }} tun0" state=present
      when: tun0 is defined

  roles:
    - docker
    - tinc
    - achaussier.ntp

  tasks:

    - name: "Allow rpcbind access to members of the VPN"
      tags:
        - security
      lineinfile:
        dest: /etc/hosts.allow
        regexp: '^rpcbind : .*'
        line: "rpcbind : {{ (tun0 | splitext)[0]}}."
        state: present

    - name: "Deny rpcbind access to everyone else"
      tags:
        - security
      lineinfile:
        dest: /etc/hosts.deny
        regexp: '^rpcbind : .*'
        line: "rpcbind : ALL"
        state: present
