---
# wordpress image
- name: Copy wordpress image to nodes storage
  copy:
    src: "{{ parcolab_wordpress_image }}.{{ parcolab_git_version }}"
    dest: /tmp/{{ parcolab_wordpress_image_name }}.{{ parcolab_git_version }}.tar
    mode: 0644

- name: Check if wordpress image exists on slaves
  command: docker images {{ parcolab_wordpress_image_name }}
  register: parcolab_wordpress_docker_images
  changed_when: False

- name: Load the wordpress image on all slaves
  action: shell docker load -i /tmp/{{ parcolab_wordpress_image_name }}.{{ parcolab_git_version }}.tar
  when: not parcolab_git_version in parcolab_wordpress_docker_images.stdout

# node image
- name: Copy node image to nodes storage
  copy:
    src: "{{ parcolab_node_image }}.{{ parcolab_git_version }}"
    dest: /tmp/{{ parcolab_node_image_name }}.{{ parcolab_git_version }}.tar
    mode: 0644

- name: Check if node image exists on slaves
  command: docker images {{ parcolab_node_image_name }}
  register: parcolab_node_docker_images
  changed_when: False

- name: Load the node image on all slaves
  action: shell docker load -i /tmp/{{ parcolab_node_image_name }}.{{ parcolab_git_version }}.tar
  when: not parcolab_git_version in parcolab_node_docker_images.stdout
