---
- name: Create mesos-ggsp-slave/
  file: path=mesos-ggsp-slave state=directory mode=0755

- name: Install python-httplib2
  # httplib2 is necessary for topface.marathon_app
  apt: name=python-httplib2

- name: Install mesos configuration file
  template:
    src: templates/mesos-config-slave.j2
    dest: mesos-ggsp-slave/config
    mode: 0440

- name: Install mesos-compose
  get_url:
    url: https://raw.githubusercontent.com/j3k0/mesos-compose/{{ mesos_version }}/compose
    dest: /usr/local/bin/mesos-compose
    mode: 0770

- name: Generate mesos-ggsp slave config
  command: mesos-compose slave
  args:
    chdir: mesos-ggsp-slave
    creates: docker-compose.yml

- name: Check if mesos-ggsp slave is running
  command: docker ps
  changed_when: False
  register: mesosslave_docker_ps

- name: Start mesos-ggsp slave
  command: docker-compose up -d --no-recreate
  args:
    chdir: mesos-ggsp-slave
  when: not 'mesosggspslave_mesosslave_1' in mesosslave_docker_ps.stdout
