---
- name: Check if docker is installed
  shell: docker info
  ignore_errors: yes
  changed_when: False
  register: docker_info

- name: Check if docker-compose is installed
  shell: docker-compose version
  ignore_errors: yes
  changed_when: False
  register: docker_compose_info

- block:
  - name: Add docker repository gpg key
    apt_key:
      keyserver: hkp://p80.pool.sks-keyservers.net:80
      id: 58118E89F3A912897C070ADBF76221572C52609D
      state: present

  - name: Add docker repository
    apt_repository:
      repo: deb https://apt.dockerproject.org/repo {{ ubuntu_version }} main
      state: present

  - name: Install docker
    apt: name=docker-engine update_cache=yes

  when: docker_info is defined and not docker_info.rc == 0

- name: Make sure docker binds to the VPN on ubuntu-trusty
  tags: [ docker_config ]
  lineinfile:
    dest: /etc/default/docker
    regexp: ^DOCKER_OPTS
    line: 'DOCKER_OPTS="{% for dns in groups["mesos-dns"] %} --dns {{ hostvars[dns].tun0 }} {% endfor %} --dns 8.8.8.8 --dns 8.8.4.4 --ip {{ tun0 }} --bip={{ docker_bip }}/16 --log-opt max-size=50m --log-opt max-file=5"'

- block:
  - name: Make sure docker binds to the VPN on ubuntu-xenial 1/2
    tags: [ docker_config ]
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
      mode: 0755

  - name: Make sure docker binds to the VPN on ubuntu-xenial 2/2
    tags: [ docker_config ]
    template:
      src: templates/docker.conf.j2
      dest: /etc/systemd/system/docker.service.d/docker.conf
      mode: 0644
  when: ubuntu_version == "ubuntu-xenial"

- name: Start docker
  service: name=docker state=started enabled=true

- block:
  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.9.0/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0770

  when: docker_compose_info is defined and not docker_compose_info.rc == 0
