---

# Tasks file for ntp

- name: Load the OS specific variables
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family }}.yml"

- include: install_debian.yml
  tags:
    - install
    - ntp
  when: ansible_os_family == "Debian"

- include: configure.yml
  tags:
    - config
    - ntp
